version: '2'

services:
  foodsservice:
    image: foodsservice
    container_name: foodsservice
    ports:
     - 8080:80
    extra_hosts:
     - mongo:10.24.66.43
     - mysql:10.24.66.43
    build:
      context: ./Foods.Service.Api
      dockerfile: Dockerfile
    depends_on:
     - "mongo"
     - "mysql"
  mongoreadyroll:
    image: mongoreadyroll
    container_name: mongoreadyroll
    extra_hosts:
     - mongo:10.24.66.43
    build:
      context: ../MongoReadyRoll
      dockerfile: Dockerfile
    depends_on:
     - "mongo"
  mongo:
    image: mongo:latest
    container_name: mongofoods
    hostname: mongo
    ports:
     - 32770:27017
  mysql:
    image: mysql:latest
    container_name: mysqlfoods
    hostname: mysql
    ports:
     - 32771:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=foodsidentity
    - MYSQL_USER=developer
    - MYSQL_PASSWORD=root